name: Daily Commit

on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Daily commit job for 22f3001788@ds.study.iitm.ac.in
        run: |
          echo "Daily log entry at $(date -u)" >> daily-log.txt
          cat daily-log.txt | tail -n 5

      - name: Git Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily automated commit at $(date -u)" || exit 0
          git push
